language: ruby
rvm:
  - 2.4.5
before_install:
  - gem install -v 2.0.2 bundler --no-rdoc --no-ri
services:
  - imagemagick
  - postgresql
before_script:
  - psql -c 'create database todo_project_test;' -U postgres
script:
  - bundle exec rails db:migrate
  - bundle exec rspec
